language: python
python:
- '3.6'
cache: pip
install:
- pip install awscli
script:
- echo "All Travis jobs need a script!"
deploy:
  on:
    branch: master
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: www.basingstoke.io
  region: eu-west-2
  local_dir: site
after_deploy:
- aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID
  --paths "/*"
env:
  global:
  - secure: jgXaNkfH2hsFHzUJc2CY3reJNtuJIy7KSzuQ8F2AJ4j6ypYyY8125Qsyq2Pd2BLZxtkc6uyy5Y+/9ntgeG4yaTlBM8RimDbRH59arJpQsC/EYNxLRFuWrlDdLcSRxzO4AOv3FqVTum5wNL77f5wXLahwqVdGrcU9ZjnmDhLpq0/vVeZkBSUukW4FTKauSl++b8zfTYBTaBDd2NXf+rLnSwgnAZrcPwjdmlTwnfaYS6IV1lPXzf8WsynMQs0yrFL71f2YJA5OV/W2JJIdo/E9+hWoh+4Q4YkKSvSw8uFanKFNprkjbudbqLc3dMOxlPSZYGH1Q4KpKZRXZBWlW31AEe90BIJEiQnIAFVuLDhdldJsz63J1Pcm1cOewy+ECdnICK3h/m/ZndULm4x2WLgwotHO/u/BcsN2/rGOMo+W1zWonuew9Axn5lNMYpcSczzzVl0czhoSggDzCsBd5zcr5cWaXsFSUgaYtSD5886g8Leg90Zwyjsn93tUMoCAw2Uz8NhhlSpHS2fjupQkYkAOz9nXAlFF+wP8Wzzo1Wvbg3IBEDP2iVceT/5ahgDrKxv+tMO2kCHYo+Nst43qZYGmwJY5aFsKCKL29mZ4iRfiI0VBxoWc7l2//DLnhl0UYz/GTprW2zW/VoIW07IuVu3o/NrOhO23+2keqykPBeEOKws=
  - secure: m+Acmot1l7+/JC9kciG/qSqnG2T/Z7+Jx01selM8SDX+peQ+r4Y0B4GYFd5ZwFMH6ezwtoa6LhL+GskshrMMvzh7NaGHbM4Q/dWJb84i6S+l5P4CNBIHcUbFpGxSpQbaAUhFKYChwiPUEB+XGwh06X9PRnm2V6j8O3Yj91a0ck5jBf0r/EdtAE6lbGCqIp/WbmNoH2nc8rkzSAgL5/XvQJYUbRf8lkl2C/xq/erwZa+Zkl90LVaMpjq9IdLBaof2a/HpXCNCl1DJjBDvuQOSildgsAD+DSU0XaFJo1ACoaY104HtXAja3b6+dOh0saEM8x64DmFfGB6fVmzsXbgkqoTvKx0llyq6lgZNo1DUYc41UHgnxczm+gES9KypFr0D/9b1AZjlfa+V/OuTi6UKIZSMCFR3N7d8QGiNWhdg9IE3rK7sFCPO+DgX9b6KLDVkFaKlPUu3MPmOTb+EG7sNRk4rV79HvZELgiFypQhwERAr6SCdfxiWtDxkegOTVary0pNu1dRkwJ4G1T6Vf+L1C7FtmaKd1RnvwaOHt4imhlqiTLfwromU72MplGqGA7T8u0J7yl359CWlRqPuE/pdGy1wzxd820/jm3kjU2EhBOmoZL3uocVUgAkO5hG2cjdxIT14VCviz/6dP65DRFqSpGpYiuUYWQMrN2CuTLU4eeI=
  - secure: HGx2ZRbLFl12B1NICIldbxMOMKSf+CNwIsEUfL4OEMWqP84aAWOz8UXjj02B2OTDsUvGh+N+QsVfD/CuZGX4cXYD7KAcq1Wzc7obR6J2bj8qgHZaOmyT5fHn8QqgFf2H4etJBF5ND/KMnlWLHO9VZtHhiPIwsPE4+0MbRymTRENF57rzT/4THE9zSGTbOkUM6S//eXq1ruYTop48qZuQYmRXqRPVDSJSk1QkWhbMNRyyGPq5gURAYAuhrKSelC18bWHW107BsTb6MRJHXuZoUvqTjjqoH7MRqlFoJg0W577lP9TY+Y1u9l/PVC+NcEj7UUxGlQhCp9mMfxEu1fj8Zlbsgp/e0uDoIk98mmDTgMvmDYfalSWU7wMAnV/7BZYSXqGBpv+5+QHlaJwJ26hgsqxhtagTC/Hrcjivni6uF3xdiLwSg6bJ1Af1saYFv2QRowcLATl1NIfhC4hPfLryQoRnlN82brfs5SD5qie171QBrgygs43Yzikw5s86PMV7JzyfLW3F0GLYYuam5qQiTSjetexM8NLwIYtm1zx18ruP9IoHXbbIMjQLW60/PG7EFTy54qAfCkfn39UY3jkC/NQD+5RbfE+af55YqR8kl/TTZSo1Rc+tITCrHV3VJfK2iSD4+MEptsueHRvpRqIWn6Lc0wK3UEDRLwGLeCSjqiY=
